### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mwpastore** [mwpastore/sinja#1]
### Meta
- [ ] Documentation
  - [x] README
  - [x] Examples
  - [ ] RDoc/YARD
- [x] Tests 😭 
  - [x] Helpers
  - [x] Utility Classes
  - [x] Middleware
  - [x] Integration
- [x] Feature comparisons (e.g. cf. [this](http://www.hark.bz/blog/post/make-your-graperails-app-json-api-compliant-cheap))
- [ ] Performance and memory analyses
- [ ] Swagger/schema.org/?? catalog/discovery integration 
  - [x] Support `HEAD` requests for method discovery and CORS
### Features
- [x] Pass-through JSONAPI::Serializer options
  - [x] Class level, root and defaults (e.g. `set :jsonapi_serializer_options, :meta => {}`)
    - [x] Inheritable?
  - [x] In return results from actions (e.g. `Post[id], :include=>:author`)
  - [x] Punch through to relationships
- [ ] JSON:API states that the server must return 400 if the client passes unhandled/able query parameters. What's a nice DSL to express this?
- [x] Logging
  - [x] Configurable progname
  - [x] Add logging where appropriate
  - [x] Audit halt/fail/raise codes and messages
- [ ] More configurables in general!
  - [ ] Strictness level
  - [x] Error messages
- [x] Control which relationships get passed through (or don't) on `create`/`update`
  - [x] Enhance `graft`/`merge` to take a `:passthru` option that can be `:create`, `:update`, or both?
- [x] Handle exceptions that should be 409
- [x] Handle exceptions that should be 422
- [x] Handle exceptions that should be 404

### Un-features
- [x] There _has_ to be a better way to delegate requests to relationship routes and bypass the after filters on the response than [this](https://github.com/mwpastore/sinja/blob/a9ca403b1998ac226e038a83c96d5ae7dd1d3e76/lib/sinatra/jsonapi/resource.rb#L53-L62)
  - Some middleware that intercepts failed requests with a certain status code and delegates to an object/class wrapped in `env`?
  - Sinatra::Namespace? **To the rescue!**
- [x] Keeping e.g. `action_roles`, `action_conflicts`, and `relationships` on the registering app's settings (class) is kind of janky. Can we do a better job of hiding this storage from the registering app? **It's still on settings but now at least it's tucked into a Config object.**
- [x] Defer extending Sinatra DSL, parameterize `ACTIONS` into a method? It's just clumsy and weird. **Well, that's a little better.**
  - [x] Don't load unnecessary relationship helps (e.g. has-many actions on has-one routes)
- [x] It's possible that requiring `show` for update, destroy, and relationships is somewhat misguided. I can see a situation where a user has access to e.g. delete something without being able to view it. Maybe we need to abstract out a "finder" helper (or unrestricted action helper) that is used by show, update, etc.?

### Known Bugs
- [x] Relationship dispatch on POST and PATCH is completely untested and probably buggy
  - [x] Null foreign keys and order of operations issue
- [x] Can't have more than one action helper of the same name per resource block :confused:
- [x] Version dependencies in gemspec need to be relaxed. Can we make this extension compatible with Sinatra 1.x?

**Comment by mwpastore** [comment]
Good enough for v1!
